version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - ${SERVER_PORT}:8080
    links:
     - "mongo:mongo"
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: